### PR TITLE
Different approach

### PR DESCRIPTION
**Pull request by ruudk**
Move .git to new target directory and use that from now.

### CODE REVIEW

**Comment by ruudk** [comment]
Is it good now?

**Comment by TomasVotruba** [comment]
The main split repository looks good :+1: 

This needs to be verified: if something is changes here 
https://github.com/symplify/github-actions/tree/master/packages/monorepo-split-github-action/.github/workflows, 

is it propadated here https://github.com/symplify/monorepo-split-github-action/tree/master/.github/workflows ?

Feel free to do any dummy change there just to trigger it

**Comment by ruudk** [comment]
I'm sure it will work, but here's the PR https://github.com/symplify/github-actions/pull/13

**Comment by ruudk** [comment]
@TomasVotruba Works https://github.com/symplify/monorepo-split-github-action/commit/6253c0b0e208c0b09724dbc2be8110374ecf8ec1 :)

**Comment by TomasVotruba** [comment]
Nice :) 

How does it perform on your monorepo split?

Btw, I've released a post about json matrix in GitHub Actions: https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions

Next will be about PHP matrix

**Pull request merged**
