### PR TITLE
Only grep .git not .github or .gitattribute

### LINKED ISSUE #6: Cleaning destination repository of old files does not clean .github and .gitattributes file
```
[NOTE] Cleaning destination repository of old files

total 20
drwx------    4 root     root          4096 Dec  2 13:26 .
drwxrwxrwt    1 root     root          4096 Dec  2 13:26 ..
drwxr-xr-x    8 root     root          4096 Dec  2 13:26 .git
-rw-r--r--    1 root     root           102 Dec  2 13:26 .gitattributes
drwxr-xr-x    2 root     root          4096 Dec  2 13:26 .github
```

I feel this command is not working properly:
```
find "$CLONE_DIR" | grep -v "^$CLONE_DIR/\.git" | grep -v "^$CLONE_DIR$" | xargs rm -rf # delete all files (to handle deletions)
```

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #6

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by ruudk** [comment]
Fails again... https://github.com/symplify/github-actions/runs/1486572983?check_suite_focus=true

**Comment by TomasVotruba** [comment]
Token is fine now, this seems related to `.git$` change

> fatal: not a git repository (or any of the parent directories): .git

**Comment by TomasVotruba** [comment]
Could you send revert of this PR to verify this?

It would not be the same scope if I do it.

**Comment by ruudk** [comment]
Did you write the original command:
```
find "$CLONE_DIR" | grep -v "^$CLONE_DIR/\.git" | grep -v "^$CLONE_DIR$" | xargs rm -rf # delete all files (to handle deletions)
```
?

**Comment by TomasVotruba** [comment]
No. I'm not very good at bash :D I probably copy pasted it from the original action:
https://github.com/cpina/github-action-push-to-another-repository/blob/976916018a4108195b74a5663a045141c6708c79/entrypoint.sh#L31

**Comment by ruudk** [comment]
Added an issue here https://github.com/cpina/github-action-push-to-another-repository/issues/16

**Pull request merged**
