### PR TITLE
Remove everything except .git - Fix

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@TomasVotruba Sorry about that. This should be the correct one.

**Comment by TomasVotruba** [comment]
No problem :) I know how tricky is to develop without testing for Github Actions.

Thank you for your work on this

**Comment by TomasVotruba** [comment]
CI fails unfortunately:
https://github.com/symplify/github-actions/runs/1488292885

image

**Comment by ruudk** [comment]
Yes, found a way to reproduce it:
https://github.com/cpina/github-action-push-to-another-repository/issues/16#issuecomment-737434600

**Pull request merged**
