### PR TITLE
Use git rm to cleanup files

### PR DESCRIPTION
**Pull request by glensc**
Use git rm to cleanup files to match files accurately: dotfiles, and paths with spaces.

### CODE REVIEW

**Comment by glensc** [comment]
Disclaimer: The changes were written in GitHub WebIDE, so not tested at all.

**Comment by glensc** [comment]
This sloppy code irritated me:

```
find "$CLONE_DIR" | grep -v "^$CLONE_DIR/\.git" | grep -v "^$CLONE_DIR$" | xargs rm -rf # delete all files (to handle deletions)
```

so, my OCD told me to rewrite it as safe code that does not croak on spaces and other variations, like a $CLONE_DIR making a regexp for grep that fails the whole pipeline.

in fact, the replacement code is simple as `git rm -r`.

**Comment by TomasVotruba** [comment]
This is way too many changes I don't understand.
Lets take it one by one. I miss the reasoning behind it, apart syntax sugar changes.

Testing must be done too, in GitHub Action here, as it took lot of time to make it work. Let's start with that.

**Comment by glensc** [comment]
the reasoning is in issue body:
- https://github.com/symplify/github-actions/pull/2#issue-525935648

and in a comment:
- https://github.com/symplify/github-actions/pull/2#issuecomment-732365927

extra comments are inlined in code, where neccessary.

**Comment by TomasVotruba** [comment]
I don't understand any of those.

**Comment by glensc** [comment]
I don't know how to explain it differently if you don't understand that this line of commands is replaced with `git rm` (said out repeatedly):

```diff
-find "$CLONE_DIR" | grep -v "^$CLONE_DIR/\.git" | grep -v "^$CLONE_DIR$" | xargs rm -rf # delete all files (to handle deletions)
+git rm -r
```

perhaps test the code and see how it works. type out commands one by one, read manual pages of commands

The previous code is fragile and breaks (for example) when there are paths with spaces in the repo.

and multiple pipes without any error checking is very bad practice. even `set -e` will not help you here, there are many edge cases, here's just one of them:
- http://stratus3d.com/blog/2019/11/29/bash-errexit-inconsistency/

and from there:
- http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by TomasVotruba** [comment]
I don't want to learn more about bash at the moment. It's good enough for now.

We'd need test for this to be merged to be sure it does what inteded to.

**Comment by glensc** [comment]
Closed without a reason? Clicked the wrong button?

**Comment by TomasVotruba** [comment]
Closed for my comment above. I won't accept changes that can break without tests and feature reasoning.

**Comment by glensc** [comment]
I explained several times that your current code is broken if the repo contains filenames with spaces.

and you seemed to respond that you refuse to read the extra links, and you don't need to read, you just need to test the new code and merge.

**Comment by TomasVotruba** [comment]
As I stated, test in CI are needed to verify the added code works and does not break anything.
Thank you for understanding.

Locking to prevent further cycling.

**Pull request closed without merging**
